--<ScriptOptions statementTerminator=";"/>

CREATE TABLE DOMAIN_CONSTRAINTS (
		CONSTRAINT_CATALOG VARCHAR(128) NOT NULL,
		CONSTRAINT_SCHEMA VARCHAR(128) NOT NULL,
		CONSTRAINT_NAME VARCHAR(128) NOT NULL,
		DOMAIN_CATALOG VARCHAR(128),
		DOMAIN_SCHEMA VARCHAR(128) NOT NULL,
		DOMAIN_NAME VARCHAR(128) NOT NULL,
		IS_DEFERRABLE VARCHAR(3) NOT NULL,
		INITIALLY_DEFERRED VARCHAR(3)
	);

CREATE TABLE SYSTEM_SCHEMAS (
		TABLE_SCHEM VARCHAR(128) NOT NULL,
		TABLE_CATALOG VARCHAR(128),
		IS_DEFAULT BOOLEAN
	);

CREATE TABLE ROLE_COLUMN_GRANTS (
		GRANTOR VARCHAR(128) NOT NULL,
		GRANTEE VARCHAR(128) NOT NULL,
		TABLE_CATALOG VARCHAR(128) NOT NULL,
		TABLE_SCHEMA VARCHAR(128) NOT NULL,
		TABLE_NAME VARCHAR(128) NOT NULL,
		COLUMN_NAME VARCHAR(128) NOT NULL,
		PRIVILEGE_TYPE VARCHAR(65536) NOT NULL,
		IS_GRANTABLE VARCHAR(3)
	);

CREATE TABLE SYSTEM_SEQUENCES (
		SEQUENCE_CATALOG VARCHAR(128) NOT NULL,
		SEQUENCE_SCHEMA VARCHAR(128) NOT NULL,
		SEQUENCE_NAME VARCHAR(128) NOT NULL,
		DATA_TYPE VARCHAR(65536),
		NUMERIC_PRECISION BIGINT,
		NUMERIC_PRECISION_RADIX BIGINT,
		NUMERIC_SCALE BIGINT,
		MAXIMUM_VALUE VARCHAR(65536),
		MINIMUM_VALUE VARCHAR(65536),
		INCREMENT VARCHAR(65536),
		CYCLE_OPTION VARCHAR(3),
		DECLARED_DATA_TYPE VARCHAR(65536),
		DECLARED_NUMERIC_PRECISION BIGINT,
		DECLARED_NUMERIC_SCALE BIGINT,
		START_WITH VARCHAR(65536),
		NEXT_VALUE VARCHAR(65536)
	);

CREATE TABLE TABLES (
		TABLE_CATALOG VARCHAR(128) NOT NULL,
		TABLE_SCHEMA VARCHAR(128) NOT NULL,
		TABLE_NAME VARCHAR(128) NOT NULL,
		TABLE_TYPE VARCHAR(65536),
		SELF_REFERENCING_COLUMN_NAME VARCHAR(128),
		REFERENCE_GENERATION VARCHAR(65536),
		USER_DEFINED_TYPE_CATALOG VARCHAR(128),
		USER_DEFINED_TYPE_SCHEMA VARCHAR(128),
		USER_DEFINED_TYPE_NAME VARCHAR(128),
		IS_INSERTABLE_INTO VARCHAR(3),
		IS_TYPED VARCHAR(3),
		COMMIT_ACTION VARCHAR(65536)
	);

CREATE TABLE SQL_PARTS (
		PART VARCHAR(65536) NOT NULL,
		NAME VARCHAR(65536),
		IS_SUPPORTED VARCHAR(3),
		IS_VERIFIED_BY VARCHAR(65536),
		COMMENTS VARCHAR(65536)
	);

CREATE TABLE CONSTRAINT_COLUMN_USAGE (
		TABLE_CATALOG VARCHAR(128) NOT NULL,
		TABLE_SCHEMA VARCHAR(128) NOT NULL,
		TABLE_NAME VARCHAR(128) NOT NULL,
		COLUMN_NAME VARCHAR(128) NOT NULL,
		CONSTRAINT_CATALOG VARCHAR(128) NOT NULL,
		CONSTRAINT_SCHEMA VARCHAR(128) NOT NULL,
		CONSTRAINT_NAME VARCHAR(128) NOT NULL
	);

CREATE TABLE SEQUENCES (
		SEQUENCE_CATALOG VARCHAR(128) NOT NULL,
		SEQUENCE_SCHEMA VARCHAR(128) NOT NULL,
		SEQUENCE_NAME VARCHAR(128) NOT NULL,
		DATA_TYPE VARCHAR(65536),
		NUMERIC_PRECISION BIGINT,
		NUMERIC_PRECISION_RADIX BIGINT,
		NUMERIC_SCALE BIGINT,
		MAXIMUM_VALUE VARCHAR(65536),
		MINIMUM_VALUE VARCHAR(65536),
		INCREMENT VARCHAR(65536),
		CYCLE_OPTION VARCHAR(3),
		DECLARED_DATA_TYPE VARCHAR(65536),
		DECLARED_NUMERIC_PRECISION BIGINT,
		DECLARED_NUMERIC_SCALE BIGINT,
		START_WITH VARCHAR(65536),
		NEXT_VALUE VARCHAR(65536)
	);

CREATE TABLE SYSTEM_COLUMNS (
		TABLE_CAT VARCHAR(128) NOT NULL,
		TABLE_SCHEM VARCHAR(128) NOT NULL,
		TABLE_NAME VARCHAR(128) NOT NULL,
		COLUMN_NAME VARCHAR(128),
		DATA_TYPE SMALLINT,
		TYPE_NAME VARCHAR(128),
		COLUMN_SIZE INTEGER,
		BUFFER_LENGTH INTEGER,
		DECIMAL_DIGITS INTEGER,
		NUM_PREC_RADIX INTEGER,
		NULLABLE INTEGER,
		REMARKS VARCHAR(65536),
		COLUMN_DEF VARCHAR(65536),
		SQL_DATA_TYPE INTEGER,
		SQL_DATETIME_SUB INTEGER,
		CHAR_OCTET_LENGTH INTEGER,
		ORDINAL_POSITION INTEGER NOT NULL,
		IS_NULLABLE VARCHAR(3),
		SCOPE_CATALOG VARCHAR(128),
		SCOPE_SCHEMA VARCHAR(128),
		SCOPE_TABLE VARCHAR(128),
		SOURCE_DATA_TYPE VARCHAR(128),
		IS_AUTOINCREMENT VARCHAR(3),
		IS_GENERATEDCOLUMN VARCHAR(3)
	);

CREATE TABLE ROLE_USAGE_GRANTS (
		GRANTOR VARCHAR(128) NOT NULL,
		GRANTEE VARCHAR(128) NOT NULL,
		OBJECT_CATALOG VARCHAR(128) NOT NULL,
		OBJECT_SCHEMA VARCHAR(128) NOT NULL,
		OBJECT_NAME VARCHAR(128) NOT NULL,
		OBJECT_TYPE VARCHAR(65536) NOT NULL,
		PRIVILEGE_TYPE VARCHAR(65536) NOT NULL,
		IS_GRANTABLE VARCHAR(3) NOT NULL
	);

CREATE TABLE USAGE_PRIVILEGES (
		GRANTOR VARCHAR(128) NOT NULL,
		GRANTEE VARCHAR(128) NOT NULL,
		OBJECT_CATALOG VARCHAR(128) NOT NULL,
		OBJECT_SCHEMA VARCHAR(128) NOT NULL,
		OBJECT_NAME VARCHAR(128) NOT NULL,
		OBJECT_TYPE VARCHAR(65536) NOT NULL,
		PRIVILEGE_TYPE VARCHAR(65536) NOT NULL,
		IS_GRANTABLE VARCHAR(3) NOT NULL
	);

CREATE TABLE ROUTINE_SEQUENCE_USAGE (
		SPECIFIC_CATALOG VARCHAR(128) NOT NULL,
		SPECIFIC_SCHEMA VARCHAR(128) NOT NULL,
		SPECIFIC_NAME VARCHAR(128) NOT NULL,
		SEQUENCE_CATALOG VARCHAR(128) NOT NULL,
		SEQUENCE_SCHEMA VARCHAR(128) NOT NULL,
		SEQUENCE_NAME VARCHAR(128) NOT NULL
	);

CREATE TABLE COLUMN_UDT_USAGE (
		UDT_CATALOG VARCHAR(128) NOT NULL,
		UDT_SCHEMA VARCHAR(128) NOT NULL,
		UDT_NAME VARCHAR(128) NOT NULL,
		TABLE_CATALOG VARCHAR(128) NOT NULL,
		TABLE_SCHEMA VARCHAR(128) NOT NULL,
		TABLE_NAME VARCHAR(128) NOT NULL,
		COLUMN_NAME VARCHAR(128) NOT NULL
	);

CREATE TABLE SYSTEM_VERSIONCOLUMNS (
		SCOPE INTEGER,
		COLUMN_NAME VARCHAR(128),
		DATA_TYPE SMALLINT,
		TYPE_NAME VARCHAR(128),
		COLUMN_SIZE SMALLINT,
		BUFFER_LENGTH INTEGER,
		DECIMAL_DIGITS SMALLINT,
		PSEUDO_COLUMN SMALLINT,
		TABLE_CAT VARCHAR(128),
		TABLE_SCHEM VARCHAR(128),
		TABLE_NAME VARCHAR(128)
	);

CREATE TABLE COLUMNS (
		TABLE_CATALOG VARCHAR(128),
		TABLE_SCHEMA VARCHAR(128) NOT NULL,
		TABLE_NAME VARCHAR(128) NOT NULL,
		COLUMN_NAME VARCHAR(128) NOT NULL,
		ORDINAL_POSITION BIGINT NOT NULL,
		COLUMN_DEFAULT VARCHAR(65536),
		IS_NULLABLE VARCHAR(3),
		DATA_TYPE VARCHAR(65536),
		CHARACTER_MAXIMUM_LENGTH BIGINT,
		CHARACTER_OCTET_LENGTH BIGINT,
		NUMERIC_PRECISION BIGINT,
		NUMERIC_PRECISION_RADIX BIGINT,
		NUMERIC_SCALE BIGINT,
		DATETIME_PRECISION BIGINT,
		INTERVAL_TYPE VARCHAR(65536),
		INTERVAL_PRECISION BIGINT,
		CHARACTER_SET_CATALOG VARCHAR(65536),
		CHARACTER_SET_SCHEMA VARCHAR(128),
		CHARACTER_SET_NAME VARCHAR(128),
		COLLATION_CATALOG VARCHAR(128),
		COLLATION_SCHEMA VARCHAR(128),
		COLLATION_NAME VARCHAR(128),
		DOMAIN_CATALOG VARCHAR(128),
		DOMAIN_SCHEMA VARCHAR(128),
		DOMAIN_NAME VARCHAR(128),
		UDT_CATALOG VARCHAR(128),
		UDT_SCHEMA VARCHAR(128),
		UDT_NAME VARCHAR(128),
		SCOPE_CATALOG VARCHAR(128),
		SCOPE_SCHEMA VARCHAR(128),
		SCOPE_NAME VARCHAR(128),
		MAXIMUM_CARDINALITY BIGINT,
		DTD_IDENTIFIER VARCHAR(128),
		IS_SELF_REFERENCING VARCHAR(3),
		IS_IDENTITY VARCHAR(3),
		IDENTITY_GENERATION VARCHAR(65536),
		IDENTITY_START VARCHAR(65536),
		IDENTITY_INCREMENT VARCHAR(65536),
		IDENTITY_MAXIMUM VARCHAR(65536),
		IDENTITY_MINIMUM VARCHAR(65536),
		IDENTITY_CYCLE VARCHAR(3),
		IS_GENERATED VARCHAR(65536),
		GENERATION_EXPRESSION VARCHAR(65536),
		IS_UPDATABLE VARCHAR(3),
		DECLARED_DATA_TYPE VARCHAR(65536),
		DECLARED_NUMERIC_PRECISION BIGINT,
		DECLARED_NUMERIC_SCALE BIGINT
	);

CREATE TABLE COLUMN_COLUMN_USAGE (
		TABLE_CATALOG VARCHAR(128) NOT NULL,
		TABLE_SCHEMA VARCHAR(128) NOT NULL,
		TABLE_NAME VARCHAR(128) NOT NULL,
		COLUMN_NAME VARCHAR(128) NOT NULL,
		DEPENDENT_COLUMN VARCHAR(128) NOT NULL
	);

CREATE TABLE ADMINISTRABLE_ROLE_AUTHORIZATIONS (
		GRANTEE VARCHAR(128) NOT NULL,
		ROLE_NAME VARCHAR(128) NOT NULL,
		IS_GRANTABLE VARCHAR(128) NOT NULL
	);

CREATE TABLE COLLATIONS (
		COLLATION_CATALOG VARCHAR(128) NOT NULL,
		COLLATION_SCHEMA VARCHAR(128) NOT NULL,
		COLLATION_NAME VARCHAR(128) NOT NULL,
		PAD_ATTRIBUTE VARCHAR(65536)
	);

CREATE TABLE COLUMN_PRIVILEGES (
		GRANTOR VARCHAR(128) NOT NULL,
		GRANTEE VARCHAR(128) NOT NULL,
		TABLE_CATALOG VARCHAR(128) NOT NULL,
		TABLE_SCHEMA VARCHAR(128) NOT NULL,
		TABLE_NAME VARCHAR(128) NOT NULL,
		COLUMN_NAME VARCHAR(128) NOT NULL,
		PRIVILEGE_TYPE VARCHAR(65536) NOT NULL,
		IS_GRANTABLE VARCHAR(3)
	);

CREATE TABLE CHECK_CONSTRAINTS (
		CONSTRAINT_CATALOG VARCHAR(128) NOT NULL,
		CONSTRAINT_SCHEMA VARCHAR(128) NOT NULL,
		CONSTRAINT_NAME VARCHAR(128) NOT NULL,
		CHECK_CLAUSE VARCHAR(65536)
	);

CREATE TABLE SYSTEM_SESSIONS (
		SESSION_ID BIGINT NOT NULL,
		CONNECTED TIMESTAMP,
		USER_NAME VARCHAR(128),
		IS_ADMIN BOOLEAN,
		AUTOCOMMIT BOOLEAN,
		READONLY BOOLEAN,
		LAST_IDENTITY BIGINT,
		SCHEMA VARCHAR(128),
		TRANSACTION BOOLEAN,
		TRANSACTION_SIZE BIGINT,
		WAITING_FOR_THIS VARCHAR(65536),
		THIS_WAITING_FOR VARCHAR(65536),
		CURRENT_STATEMENT VARCHAR(65536),
		LATCH_COUNT BIGINT
	);

CREATE TABLE VIEW_COLUMN_USAGE (
		VIEW_CATALOG VARCHAR(128) NOT NULL,
		VIEW_SCHEMA VARCHAR(128) NOT NULL,
		VIEW_NAME VARCHAR(128) NOT NULL,
		TABLE_CATALOG VARCHAR(128) NOT NULL,
		TABLE_SCHEMA VARCHAR(128) NOT NULL,
		TABLE_NAME VARCHAR(128) NOT NULL,
		COLUMN_NAME VARCHAR(128) NOT NULL
	);

CREATE TABLE SYSTEM_CROSSREFERENCE (
		PKTABLE_CAT VARCHAR(128),
		PKTABLE_SCHEM VARCHAR(128),
		PKTABLE_NAME VARCHAR(128),
		PKCOLUMN_NAME VARCHAR(128),
		FKTABLE_CAT VARCHAR(128) NOT NULL,
		FKTABLE_SCHEM VARCHAR(128) NOT NULL,
		FKTABLE_NAME VARCHAR(128) NOT NULL,
		FKCOLUMN_NAME VARCHAR(128),
		KEY_SEQ SMALLINT NOT NULL,
		UPDATE_RULE SMALLINT,
		DELETE_RULE SMALLINT,
		FK_NAME VARCHAR(128) NOT NULL,
		PK_NAME VARCHAR(128),
		DEFERRABILITY SMALLINT
	);

CREATE TABLE INFORMATION_SCHEMA_CATALOG_NAME (
		CATALOG_NAME VARCHAR(128) NOT NULL
	);

CREATE TABLE JAR_JAR_USAGE (
		PATH_JAR_CATALOG VARCHAR(128) NOT NULL,
		PATH_JAR_SCHAMA VARCHAR(128) NOT NULL,
		PATH_JAR_NAME VARCHAR(128) NOT NULL,
		JAR_CATALOG VARCHAR(128) NOT NULL,
		JAR_SCHEMA VARCHAR(128) NOT NULL,
		JAR_NAME VARCHAR(128) NOT NULL
	);

CREATE TABLE SYSTEM_CACHEINFO (
		CACHE_FILE VARCHAR(65536) NOT NULL,
		MAX_CACHE_COUNT BIGINT,
		MAX_CACHE_BYTES BIGINT,
		CACHE_SIZE BIGINT,
		CACHE_BYTES BIGINT,
		FILE_FREE_BYTES BIGINT,
		FILE_FREE_COUNT BIGINT,
		FILE_FREE_POS BIGINT
	);

CREATE TABLE JARS (
		JAR_CATALOG VARCHAR(128) NOT NULL,
		JAR_SCHEMA VARCHAR(128) NOT NULL,
		JAR_NAME VARCHAR(128) NOT NULL,
		JAR_PATH VARCHAR(65536) NOT NULL
	);

CREATE TABLE TABLE_PRIVILEGES (
		GRANTOR VARCHAR(128) NOT NULL,
		GRANTEE VARCHAR(128) NOT NULL,
		TABLE_CATALOG VARCHAR(128) NOT NULL,
		TABLE_SCHEMA VARCHAR(128) NOT NULL,
		TABLE_NAME VARCHAR(128) NOT NULL,
		PRIVILEGE_TYPE VARCHAR(65536) NOT NULL,
		IS_GRANTABLE VARCHAR(3) NOT NULL,
		WITH_HIERARCHY VARCHAR(3)
	);

CREATE TABLE TRIGGERED_UPDATE_COLUMNS (
		TRIGGER_CATALOG VARCHAR(128) NOT NULL,
		TRIGGER_SCHEMA VARCHAR(128) NOT NULL,
		TRIGGER_NAME VARCHAR(128) NOT NULL,
		EVENT_OBJECT_CATALOG VARCHAR(128) NOT NULL,
		EVENT_OBJECT_SCHEMA VARCHAR(128) NOT NULL,
		EVENT_OBJECT_TABLE VARCHAR(128) NOT NULL,
		EVENT_OBJECT_COLUMN VARCHAR(128) NOT NULL
	);

CREATE TABLE BLOCKS (
		BLOCK_ADDR INTEGER NOT NULL,
		BLOCK_COUNT INTEGER NOT NULL,
		TX_ID BIGINT NOT NULL
	);

CREATE TABLE SYSTEM_BESTROWIDENTIFIER (
		SCOPE SMALLINT NOT NULL,
		COLUMN_NAME VARCHAR(128) NOT NULL,
		DATA_TYPE SMALLINT,
		TYPE_NAME VARCHAR(128),
		COLUMN_SIZE INTEGER,
		BUFFER_LENGTH INTEGER,
		DECIMAL_DIGITS SMALLINT,
		PSEUDO_COLUMN SMALLINT,
		TABLE_CAT VARCHAR(128) NOT NULL,
		TABLE_SCHEM VARCHAR(128) NOT NULL,
		TABLE_NAME VARCHAR(128) NOT NULL,
		NULLABLE SMALLINT,
		IN_KEY BOOLEAN
	);

CREATE TABLE SYSTEM_SESSIONINFO (
		KEY VARCHAR(65536) NOT NULL,
		VALUE VARCHAR(65536)
	);

CREATE TABLE ROLE_ROUTINE_GRANTS (
		GRANTOR VARCHAR(128) NOT NULL,
		GRANTEE VARCHAR(128) NOT NULL,
		SPECIFIC_CATALOG VARCHAR(128) NOT NULL,
		SPECIFIC_SCHEMA VARCHAR(128) NOT NULL,
		SPECIFIC_NAME VARCHAR(128) NOT NULL,
		ROUTINE_CATALOG VARCHAR(128) NOT NULL,
		ROUTINE_SCHEMA VARCHAR(128) NOT NULL,
		ROUTINE_NAME VARCHAR(128) NOT NULL,
		PRIVILEGE_TYPE VARCHAR(65536) NOT NULL,
		IS_GRANTABLE VARCHAR(3) NOT NULL
	);

CREATE TABLE SCHEMATA (
		CATALOG_NAME VARCHAR(128) NOT NULL,
		SCHEMA_NAME VARCHAR(128) NOT NULL,
		SCHEMA_OWNER VARCHAR(128),
		DEFAULT_CHARACTER_SET_CATALOG VARCHAR(128),
		DEFAULT_CHARACTER_SET_SCHEMA VARCHAR(128),
		DEFAULT_CHARACTER_SET_NAME VARCHAR(128),
		SQL_PATH VARCHAR(65536)
	);

CREATE TABLE SYSTEM_USERS (
		USER_NAME VARCHAR(128) NOT NULL,
		ADMIN BOOLEAN,
		INITIAL_SCHEMA VARCHAR(128),
		AUTHENTICATION VARCHAR(128),
		PASSWORD_DIGEST VARCHAR(128)
	);

CREATE TABLE CHECK_CONSTRAINT_ROUTINE_USAGE (
		CONSTRAINT_CATALOG VARCHAR(128) NOT NULL,
		CONSTRAINT_SCHEMA VARCHAR(128) NOT NULL,
		CONSTRAINT_NAME VARCHAR(128) NOT NULL,
		SPECIFIC_CATALOG VARCHAR(128) NOT NULL,
		SPECIFIC_SCHEMA VARCHAR(128) NOT NULL,
		SPECIFIC_NAME VARCHAR(128) NOT NULL
	);

CREATE TABLE LOB_IDS (
		LOB_ID BIGINT NOT NULL,
		LOB_LENGTH BIGINT NOT NULL,
		LOB_USAGE_COUNT INTEGER DEFAULT 0 NOT NULL,
		LOB_TYPE SMALLINT NOT NULL
	);

CREATE TABLE TRANSLATIONS (
		TRANSLATION_CATALOG VARCHAR(128) NOT NULL,
		TRANSLATION_SCHEMA VARCHAR(128) NOT NULL,
		TRANSLATION_NAME VARCHAR(128) NOT NULL,
		SOURCE_CHARACTER_SET_CATALOG VARCHAR(128),
		SOURCE_CHARACTER_SET_SCHEMA VARCHAR(128),
		SOURCE_CHARACTER_SET_NAME VARCHAR(128),
		TARGET_CHARACTER_SET_CATALOG VARCHAR(128),
		TARGET_CHARACTER_SET_SCHEMA VARCHAR(128),
		TARGET_CHARACTER_SET_NAME VARCHAR(128),
		TRANSLATION_SOURCE_CATALOG VARCHAR(128),
		TRANSLATION_SOURCE_SCHEMA VARCHAR(128),
		TRANSLATION_SOURCE_NAME VARCHAR(128)
	);

CREATE TABLE VIEW_TABLE_USAGE (
		VIEW_CATALOG VARCHAR(128) NOT NULL,
		VIEW_SCHEMA VARCHAR(128) NOT NULL,
		VIEW_NAME VARCHAR(128) NOT NULL,
		TABLE_CATALOG VARCHAR(128) NOT NULL,
		TABLE_SCHEMA VARCHAR(128) NOT NULL,
		TABLE_NAME VARCHAR(128) NOT NULL
	);

CREATE TABLE SYSTEM_TABLES (
		TABLE_CAT VARCHAR(128) NOT NULL,
		TABLE_SCHEM VARCHAR(128) NOT NULL,
		TABLE_NAME VARCHAR(128) NOT NULL,
		TABLE_TYPE VARCHAR(65536) NOT NULL,
		REMARKS VARCHAR(65536),
		TYPE_CAT VARCHAR(128),
		TYPE_SCHEM VARCHAR(128),
		TYPE_NAME VARCHAR(128),
		SELF_REFERENCING_COL_NAME VARCHAR(128),
		REF_GENERATION VARCHAR(65536),
		HSQLDB_TYPE VARCHAR(128),
		READ_ONLY BOOLEAN,
		COMMIT_ACTION VARCHAR(65536)
	);

CREATE TABLE ROLE_AUTHORIZATION_DESCRIPTORS (
		ROLE_NAME VARCHAR(128) NOT NULL,
		GRANTEE VARCHAR(128) NOT NULL,
		GRANTOR VARCHAR(128),
		IS_GRANTABLE VARCHAR(3)
	);

CREATE TABLE SYSTEM_TEXTTABLES (
		TABLE_CAT VARCHAR(128) NOT NULL,
		TABLE_SCHEM VARCHAR(128) NOT NULL,
		TABLE_NAME VARCHAR(128) NOT NULL,
		DATA_SOURCE_DEFINTION VARCHAR(65536),
		FILE_PATH VARCHAR(65536),
		FILE_ENCODING VARCHAR(65536),
		FIELD_SEPARATOR VARCHAR(65536),
		VARCHAR_SEPARATOR VARCHAR(65536),
		LONGVARCHAR_SEPARATOR VARCHAR(65536),
		IS_IGNORE_FIRST BOOLEAN,
		IS_ALL_QUOTED BOOLEAN,
		IS_QUOTED BOOLEAN,
		IS_DESC BOOLEAN
	);

CREATE TABLE SYSTEM_PROPERTIES (
		PROPERTY_SCOPE VARCHAR(65536) NOT NULL,
		PROPERTY_NAMESPACE VARCHAR(65536) NOT NULL,
		PROPERTY_NAME VARCHAR(65536) NOT NULL,
		PROPERTY_VALUE VARCHAR(65536),
		PROPERTY_CLASS VARCHAR(65536)
	);

CREATE TABLE ROUTINE_JAR_USAGE (
		SPECIFIC_CATALOG VARCHAR(128) NOT NULL,
		SPECIFIC_SCHEMA VARCHAR(128) NOT NULL,
		SPECIFIC_NAME VARCHAR(128) NOT NULL,
		JAR_CATALOG VARCHAR(128) NOT NULL,
		JAR_SCHEMA VARCHAR(128) NOT NULL,
		JAR_NAME VARCHAR(128) NOT NULL
	);

CREATE TABLE REFERENTIAL_CONSTRAINTS (
		CONSTRAINT_CATALOG VARCHAR(128) NOT NULL,
		CONSTRAINT_SCHEMA VARCHAR(128) NOT NULL,
		CONSTRAINT_NAME VARCHAR(128) NOT NULL,
		UNIQUE_CONSTRAINT_CATALOG VARCHAR(128),
		UNIQUE_CONSTRAINT_SCHEMA VARCHAR(128),
		UNIQUE_CONSTRAINT_NAME VARCHAR(128),
		MATCH_OPTION VARCHAR(65536),
		UPDATE_RULE VARCHAR(65536),
		DELETE_RULE VARCHAR(65536)
	);

CREATE TABLE ROUTINE_COLUMN_USAGE (
		SPECIFIC_CATALOG VARCHAR(128) NOT NULL,
		SPECIFIC_SCHEMA VARCHAR(128) NOT NULL,
		SPECIFIC_NAME VARCHAR(128) NOT NULL,
		ROUTINE_CATALOG VARCHAR(128) NOT NULL,
		ROUTINE_SCHEMA VARCHAR(128) NOT NULL,
		ROUTINE_NAME VARCHAR(128) NOT NULL,
		TABLE_CATALOG VARCHAR(128) NOT NULL,
		TABLE_SCHEMA VARCHAR(128) NOT NULL,
		TABLE_NAME VARCHAR(128) NOT NULL,
		COLUMN_NAME VARCHAR(128) NOT NULL
	);

CREATE TABLE SYSTEM_COMMENTS (
		OBJECT_CATALOG VARCHAR(128) NOT NULL,
		OBJECT_SCHEMA VARCHAR(128) NOT NULL,
		OBJECT_NAME VARCHAR(128) NOT NULL,
		OBJECT_TYPE VARCHAR(128) NOT NULL,
		COLUMN_NAME VARCHAR(128) NOT NULL,
		COMMENT VARCHAR(65536)
	);

CREATE TABLE ELEMENT_TYPES (
		OBJECT_CATALOG VARCHAR(128) NOT NULL,
		OBJECT_SCHEMA VARCHAR(128) NOT NULL,
		OBJECT_NAME VARCHAR(128) NOT NULL,
		OBJECT_TYPE VARCHAR(128),
		COLLECTION_TYPE_IDENTIFIER VARCHAR(128) NOT NULL,
		DATA_TYPE VARCHAR(128) NOT NULL,
		CHARACTER_MAXIMUM_LENGTH BIGINT,
		CHARACTER_OCTET_LENGTH BIGINT,
		CHARACTER_SET_CATALOG VARCHAR(128),
		CHARACTER_SET_SCHEMA VARCHAR(128),
		CHARACTER_SET_NAME VARCHAR(128),
		COLLATION_CATALOG VARCHAR(128),
		COLLATION_SCHEMA VARCHAR(128),
		COLLATION_NAME VARCHAR(128),
		NUMERIC_PRECISION BIGINT,
		NUMERIC_PRECISION_RADIX BIGINT,
		NUMERIC_SCALE BIGINT,
		DATETIME_PRECISION BIGINT,
		INTERVAL_TYPE VARCHAR(65536),
		INTERVAL_PRECISION BIGINT,
		UDT_CATALOG VARCHAR(128),
		UDT_SCHEMA VARCHAR(128),
		UDT_NAME VARCHAR(128),
		SCOPE_CATALOG VARCHAR(128),
		SCOPE_SCHEMA VARCHAR(128),
		SCOPE_NAME VARCHAR(128),
		MAXIMUM_CARDINALITY BIGINT,
		DTD_IDENTIFIER VARCHAR(128) NOT NULL,
		DECLARED_DATA_TYPE VARCHAR(65536),
		DECLARED_NUMERIC_PRECISION BIGINT,
		DECLARED_NUMERIC_SCALE BIGINT
	);

CREATE TABLE APPLICABLE_ROLES (
		GRANTEE VARCHAR(128) NOT NULL,
		ROLE_NAME VARCHAR(128) NOT NULL,
		IS_GRANTABLE VARCHAR(128) NOT NULL
	);

CREATE TABLE SYSTEM_PROCEDURES (
		PROCEDURE_CAT VARCHAR(128) NOT NULL,
		PROCEDURE_SCHEM VARCHAR(128) NOT NULL,
		PROCEDURE_NAME VARCHAR(128) NOT NULL,
		COL_4 INTEGER,
		COL_5 INTEGER,
		COL_6 INTEGER,
		REMARKS VARCHAR(65536),
		PROCEDURE_TYPE SMALLINT,
		SPECIFIC_NAME VARCHAR(128) NOT NULL
	);

CREATE TABLE SQL_IMPLEMENTATION_INFO (
		IMPLEMENTATION_INFO_ID BIGINT NOT NULL,
		IMPLEMENTATION_INFO_NAME VARCHAR(65536),
		INTEGER_VALUE BIGINT,
		CHARACTER_VALUE VARCHAR(65536),
		COMMENTS VARCHAR(65536)
	);

CREATE TABLE SQL_SIZING_PROFILES (
		SIZING_ID BIGINT NOT NULL,
		SIZING_NAME VARCHAR(65536),
		PROFILE_ID BIGINT,
		PROFILE_NAME VARCHAR(65536),
		REQUIRED_VALUE BIGINT,
		COMMENTS VARCHAR(65536)
	);

CREATE TABLE ROUTINE_PRIVILEGES (
		GRANTOR VARCHAR(128) NOT NULL,
		GRANTEE VARCHAR(128) NOT NULL,
		SPECIFIC_CATALOG VARCHAR(128) NOT NULL,
		SPECIFIC_SCHEMA VARCHAR(128) NOT NULL,
		SPECIFIC_NAME VARCHAR(128) NOT NULL,
		ROUTINE_CATALOG VARCHAR(128) NOT NULL,
		ROUTINE_SCHEMA VARCHAR(128) NOT NULL,
		ROUTINE_NAME VARCHAR(128) NOT NULL,
		PRIVILEGE_TYPE VARCHAR(65536) NOT NULL,
		IS_GRANTABLE VARCHAR(3) NOT NULL
	);

CREATE TABLE ROLE_TABLE_GRANTS (
		GRANTOR VARCHAR(128) NOT NULL,
		GRANTEE VARCHAR(128) NOT NULL,
		TABLE_CATALOG VARCHAR(128),
		TABLE_SCHEMA VARCHAR(128) NOT NULL,
		TABLE_NAME VARCHAR(128) NOT NULL,
		PRIVILEGE_TYPE VARCHAR(65536) NOT NULL,
		IS_GRANTABLE VARCHAR(3),
		WITH_HIERARCHY VARCHAR(3)
	);

CREATE TABLE CONSTRAINT_TABLE_USAGE (
		TABLE_CATALOG VARCHAR(128) NOT NULL,
		TABLE_SCHEMA VARCHAR(128) NOT NULL,
		TABLE_NAME VARCHAR(128) NOT NULL,
		CONSTRAINT_CATALOG VARCHAR(128) NOT NULL,
		CONSTRAINT_SCHEMA VARCHAR(128) NOT NULL,
		CONSTRAINT_NAME VARCHAR(128) NOT NULL
	);

CREATE TABLE USER_DEFINED_TYPES (
		USER_DEFINED_TYPE_CATALOG VARCHAR(128) NOT NULL,
		USER_DEFINED_TYPE_SCHEMA VARCHAR(128) NOT NULL,
		USER_DEFINED_TYPE_NAME VARCHAR(128) NOT NULL,
		USER_DEFINED_TYPE_CATEGORY VARCHAR(128),
		IS_INSTANTIABLE VARCHAR(3) NOT NULL,
		IS_FINAL VARCHAR(3) NOT NULL,
		ORDERING_FORM VARCHAR(128) NOT NULL,
		ORDERING_CATEGORY VARCHAR(128),
		ORDERING_ROUTINE_CATALOG VARCHAR(128),
		ORDERING_ROUTINE_SCHEMA VARCHAR(128),
		ORDERING_ROUTINE_NAME VARCHAR(128),
		REFERENCE_TYPE VARCHAR(128),
		DATA_TYPE VARCHAR(65536),
		CHARACTER_MAXIMUM_LENGTH BIGINT,
		CHARACTER_OCTET_LENGTH BIGINT,
		CHARACTER_SET_CATALOG VARCHAR(128),
		CHARACTER_SET_SCHEMA VARCHAR(128),
		CHARACTER_SET_NAME VARCHAR(128),
		COLLATION_CATALOG VARCHAR(128),
		COLLATION_SCHEMA VARCHAR(128),
		COLLATION_NAME VARCHAR(128),
		NUMERIC_PRECISION BIGINT,
		NUMERIC_PRECISION_RADIX BIGINT,
		NUMERIC_SCALE BIGINT,
		DATETIME_PRECISION BIGINT,
		INTERVAL_TYPE VARCHAR(65536),
		INTERVAL_PRECISION BIGINT,
		SOURCE_DTD_IDENTIFIER VARCHAR(65536),
		REF_DTD_IDENTIFIER VARCHAR(65536),
		DECLARED_DATA_TYPE VARCHAR(65536),
		DECLARED_NUMERIC_PRECISION BIGINT,
		DECLARED_NUMERIC_SCALE BIGINT,
		MAXIMUM_CARDINALITY BIGINT,
		EXTERNAL_NAME VARCHAR(65536),
		EXTERNAL_LANGUAGE VARCHAR(65536),
		JAVA_INTERFACE VARCHAR(65536)
	);

CREATE TABLE ROUTINE_TABLE_USAGE (
		SPECIFIC_CATALOG VARCHAR(128) NOT NULL,
		SPECIFIC_SCHEMA VARCHAR(128) NOT NULL,
		SPECIFIC_NAME VARCHAR(128) NOT NULL,
		ROUTINE_CATALOG VARCHAR(128) NOT NULL,
		ROUTINE_SCHEMA VARCHAR(128) NOT NULL,
		ROUTINE_NAME VARCHAR(128) NOT NULL,
		TABLE_CATALOG VARCHAR(128) NOT NULL,
		TABLE_SCHEMA VARCHAR(128) NOT NULL,
		TABLE_NAME VARCHAR(128) NOT NULL
	);

CREATE TABLE PARAMETERS (
		SPECIFIC_CATALOG VARCHAR(128) NOT NULL,
		SPECIFIC_SCHEMA VARCHAR(128) NOT NULL,
		SPECIFIC_NAME VARCHAR(128) NOT NULL,
		ORDINAL_POSITION BIGINT NOT NULL,
		PARAMETER_MODE VARCHAR(65536),
		IS_RESULT VARCHAR(3),
		AS_LOCATOR VARCHAR(3),
		PARAMETER_NAME VARCHAR(128),
		FROM_SQL_SPECIFIC_CATALOG VARCHAR(128),
		FROM_SQL_SPECIFIC_SCHEMA VARCHAR(128),
		FROM_SQL_SPECIFIC_NAME VARCHAR(128),
		TO_SQL_SPECIFIC_CATALOG VARCHAR(128),
		TO_SQL_SPECIFIC_SCHEMA VARCHAR(128),
		TO_SQL_SPECIFIC_NAME VARCHAR(128),
		DATA_TYPE VARCHAR(65536),
		CHARACTER_MAXIMUM_LENGTH BIGINT,
		CHARACTER_OCTET_LENGTH BIGINT,
		CHARACTER_SET_CATALOG VARCHAR(65536),
		CHARACTER_SET_SCHEMA VARCHAR(128),
		CHARACTER_SET_NAME VARCHAR(128),
		COLLATION_CATALOG VARCHAR(128),
		COLLATION_SCHEMA VARCHAR(128),
		COLLATION_NAME VARCHAR(128),
		NUMERIC_PRECISION BIGINT,
		NUMERIC_PRECISION_RADIX BIGINT,
		NUMERIC_SCALE BIGINT,
		DATETIME_PRECISION BIGINT,
		INTERVAL_TYPE VARCHAR(65536),
		INTERVAL_PRECISION BIGINT,
		UDT_CATALOG VARCHAR(128),
		UDT_SCHEMA VARCHAR(128),
		UDT_NAME VARCHAR(128),
		SCOPE_CATALOG VARCHAR(128),
		SCOPE_SCHEMA VARCHAR(128),
		SCOPE_NAME VARCHAR(128),
		MAXIMUM_CARDINALITY BIGINT,
		DTD_IDENTIFIER VARCHAR(128),
		DECLARED_DATA_TYPE VARCHAR(65536),
		DECLARED_NUMERIC_PRECISION BIGINT,
		DECLARED_NUMERIC_SCALE BIGINT
	);

CREATE TABLE SQL_SIZING (
		SIZING_ID BIGINT NOT NULL,
		SIZING_NAME VARCHAR(65536),
		SUPPORTED_VALUE BIGINT,
		COMMENTS VARCHAR(65536)
	);

CREATE TABLE SYSTEM_TYPEINFO (
		TYPE_NAME VARCHAR(128) NOT NULL,
		DATA_TYPE SMALLINT NOT NULL,
		PRECISION INTEGER,
		LITERAL_PREFIX VARCHAR(65536),
		LITERAL_SUFFIX VARCHAR(65536),
		CREATE_PARAMS VARCHAR(65536),
		NULLABLE SMALLINT,
		CASE_SENSITIVE BOOLEAN,
		SEARCHABLE INTEGER,
		UNSIGNED_ATTRIBUTE BOOLEAN,
		FIXED_PREC_SCALE BOOLEAN,
		AUTO_INCREMENT BOOLEAN,
		LOCAL_TYPE_NAME VARCHAR(128),
		MINIMUM_SCALE SMALLINT,
		MAXIMUM_SCALE SMALLINT,
		SQL_DATA_TYPE INTEGER,
		SQL_DATETIME_SUB INTEGER,
		NUM_PREC_RADIX INTEGER,
		INTERVAL_PRECISION INTEGER
	);

CREATE TABLE SYSTEM_INDEXINFO (
		TABLE_CAT VARCHAR(128) NOT NULL,
		TABLE_SCHEM VARCHAR(128) NOT NULL,
		TABLE_NAME VARCHAR(128) NOT NULL,
		NON_UNIQUE BOOLEAN NOT NULL,
		INDEX_QUALIFIER VARCHAR(128) NOT NULL,
		INDEX_NAME VARCHAR(128) NOT NULL,
		TYPE SMALLINT,
		ORDINAL_POSITION SMALLINT NOT NULL,
		COLUMN_NAME VARCHAR(128),
		ASC_OR_DESC VARCHAR(65536),
		CARDINALITY INTEGER,
		PAGES INTEGER,
		FILTER_CONDITION VARCHAR(65536),
		ROW_CARDINALITY INTEGER
	);

CREATE TABLE ROUTINES (
		SPECIFIC_CATALOG VARCHAR(128) NOT NULL,
		SPECIFIC_SCHEMA VARCHAR(128) NOT NULL,
		SPECIFIC_NAME VARCHAR(128) NOT NULL,
		ROUTINE_CATALOG VARCHAR(128) NOT NULL,
		ROUTINE_SCHEMA VARCHAR(128) NOT NULL,
		ROUTINE_NAME VARCHAR(128) NOT NULL,
		ROUTINE_TYPE VARCHAR(65536),
		MODULE_CATALOG VARCHAR(128),
		MODULE_SCHEMA VARCHAR(128),
		MODULE_NAME VARCHAR(128),
		UDT_CATALOG VARCHAR(128),
		UDT_SCHEMA VARCHAR(128),
		UDT_NAME VARCHAR(128),
		DATA_TYPE VARCHAR(65536),
		CHARACTER_MAXIMUM_LENGTH BIGINT,
		CHARACTER_OCTET_LENGTH BIGINT,
		CHARACTER_SET_CATALOG VARCHAR(128),
		CHARACTER_SET_SCHEMA VARCHAR(128),
		CHARACTER_SET_NAME VARCHAR(128),
		COLLATION_CATALOG VARCHAR(128),
		COLLATION_SCHEMA VARCHAR(128),
		COLLATION_NAME VARCHAR(128),
		NUMERIC_PRECISION BIGINT,
		NUMERIC_PRECISION_RADIX BIGINT,
		NUMERIC_SCALE BIGINT,
		DATETIME_PRECISION BIGINT,
		INTERVAL_TYPE VARCHAR(65536),
		INTERVAL_PRECISION BIGINT,
		TYPE_UDT_CATALOG VARCHAR(128),
		TYPE_UDT_SCHEMA VARCHAR(128),
		TYPE_UDT_NAME VARCHAR(128),
		SCOPE_CATALOG VARCHAR(128),
		SCOPE_SCHEMA VARCHAR(128),
		SCOPE_NAME VARCHAR(128),
		MAXIMUM_CARDINALITY BIGINT,
		DTD_IDENTIFIER VARCHAR(128),
		ROUTINE_BODY VARCHAR(65536),
		ROUTINE_DEFINITION VARCHAR(65536),
		EXTERNAL_NAME VARCHAR(65536),
		EXTERNAL_LANGUAGE VARCHAR(65536),
		PARAMETER_STYLE VARCHAR(65536),
		IS_DETERMINISTIC VARCHAR(3),
		SQL_DATA_ACCESS VARCHAR(65536),
		IS_NULL_CALL VARCHAR(3),
		SQL_PATH VARCHAR(65536),
		SCHEMA_LEVEL_ROUTINE VARCHAR(3),
		MAX_DYNAMIC_RESULT_SETS BIGINT,
		IS_USER_DEFINED_CAST VARCHAR(3),
		IS_IMPLICITLY_INVOCABLE VARCHAR(3),
		SECURITY_TYPE VARCHAR(65536),
		TO_SQL_SPECIFIC_CATALOG VARCHAR(128),
		TO_SQL_SPECIFIC_SCHEMA VARCHAR(128),
		TO_SQL_SPECIFIC_NAME VARCHAR(128),
		AS_LOCATOR VARCHAR(3),
		CREATED TIMESTAMP,
		LAST_ALTERED TIMESTAMP,
		NEW_SAVEPOINT_LEVEL VARCHAR(3),
		IS_UDT_DEPENDENT VARCHAR(3),
		RESULT_CAST_FROM_DATA_TYPE VARCHAR(65536),
		RESULT_CAST_AS_LOCATOR VARCHAR(3),
		RESULT_CAST_CHAR_MAX_LENGTH BIGINT,
		RESULT_CAST_CHAR_OCTET_LENGTH BIGINT,
		RESULT_CAST_CHAR_SET_CATALOG VARCHAR(65536),
		RESULT_CAST_CHAR_SET_SCHEMA VARCHAR(128),
		RESULT_CAST_CHARACTER_SET_NAME VARCHAR(128),
		RESULT_CAST_COLLATION_CATALOG VARCHAR(128),
		RESULT_CAST_COLLATION_SCHEMA VARCHAR(128),
		RESULT_CAST_COLLATION_NAME VARCHAR(128),
		RESULT_CAST_NUMERIC_PRECISION BIGINT,
		RESULT_CAST_NUMERIC_RADIX BIGINT,
		RESULT_CAST_NUMERIC_SCALE BIGINT,
		RESULT_CAST_DATETIME_PRECISION BIGINT,
		RESULT_CAST_INTERVAL_TYPE VARCHAR(65536),
		RESULT_CAST_INTERVAL_PRECISION BIGINT,
		RESULT_CAST_TYPE_UDT_CATALOG VARCHAR(128),
		RESULT_CAST_TYPE_UDT_SCHEMA VARCHAR(128),
		RESULT_CAST_TYPE_UDT_NAME VARCHAR(128),
		RESULT_CAST_SCOPE_CATALOG VARCHAR(128),
		RESULT_CAST_SCOPE_SCHEMA VARCHAR(128),
		RESULT_CAST_SCOPE_NAME VARCHAR(128),
		RESULT_CAST_MAX_CARDINALITY BIGINT,
		RESULT_CAST_DTD_IDENTIFIER VARCHAR(65536),
		DECLARED_DATA_TYPE VARCHAR(65536),
		DECLARED_NUMERIC_PRECISION BIGINT,
		DECLARED_NUMERIC_SCALE BIGINT,
		RESULT_CAST_FROM_DECLARED_DATA_TYPE VARCHAR(65536),
		RESULT_CAST_DECLARED_NUMERIC_PRECISION BIGINT,
		RESULT_CAST_DECLARED_NUMERIC_SCALE BIGINT
	);

CREATE TABLE SYSTEM_UDTS (
		TYPE_CAT VARCHAR(128),
		TYPE_SCHEM VARCHAR(128),
		TYPE_NAME VARCHAR(128),
		CLASS_NAME VARCHAR(65536),
		DATA_TYPE INTEGER,
		REMARKS VARCHAR(65536),
		BASE_TYPE SMALLINT
	);

CREATE TABLE VIEWS (
		TABLE_CATALOG VARCHAR(128) NOT NULL,
		TABLE_SCHEMA VARCHAR(128) NOT NULL,
		TABLE_NAME VARCHAR(128) NOT NULL,
		VIEW_DEFINITION VARCHAR(65536),
		CHECK_OPTION VARCHAR(65536),
		IS_UPDATABLE VARCHAR(3),
		INSERTABLE_INTO VARCHAR(3),
		IS_TRIGGER_UPDATABLE VARCHAR(3),
		IS_TRIGGER_DELETABLE VARCHAR(3),
		IS_TRIGGER_INSERTABLE_INTO VARCHAR(3)
	);

CREATE TABLE SYSTEM_CONNECTION_PROPERTIES (
		NAME VARCHAR(128) NOT NULL,
		MAX_LEN INTEGER,
		DEFAULT_VALUE VARCHAR(128),
		DESCRIPTION VARCHAR(128)
	);

CREATE TABLE DOMAINS (
		DOMAIN_CATALOG VARCHAR(128) NOT NULL,
		DOMAIN_SCHEMA VARCHAR(128) NOT NULL,
		DOMAIN_NAME VARCHAR(128) NOT NULL,
		DATA_TYPE VARCHAR(128),
		CHARACTER_MAXIMUM_LENGTH BIGINT NOT NULL,
		CHARACTER_OCTET_LENGTH BIGINT NOT NULL,
		CHARACTER_SET_CATALOG VARCHAR(128) NOT NULL,
		CHARACTER_SET_SCHEMA VARCHAR(128),
		CHARACTER_SET_NAME VARCHAR(128),
		COLLATION_CATALOG VARCHAR(128),
		COLLATION_SCHEMA VARCHAR(128),
		COLLATION_NAME VARCHAR(128),
		NUMERIC_PRECISION BIGINT,
		NUMERIC_PRECISION_RADIX BIGINT,
		NUMERIC_SCALE BIGINT,
		DATETIME_PRECISION BIGINT,
		INTERVAL_TYPE VARCHAR(65536),
		INTERVAL_PRECISION BIGINT,
		DOMAIN_DEFAULT VARCHAR(65536),
		MAXIMUM_CARDINALITY BIGINT,
		DTD_IDENTIFIER VARCHAR(128),
		DECLARED_DATA_TYPE VARCHAR(65536),
		DECLARED_NUMERIC_PRECISION BIGINT,
		DECLARED_NUMERIC_SCALE BIGINT
	);

CREATE TABLE TABLE_CONSTRAINTS (
		CONSTRAINT_CATALOG VARCHAR(128) NOT NULL,
		CONSTRAINT_SCHEMA VARCHAR(128) NOT NULL,
		CONSTRAINT_NAME VARCHAR(128) NOT NULL,
		CONSTRAINT_TYPE VARCHAR(65536),
		TABLE_CATALOG VARCHAR(128) NOT NULL,
		TABLE_SCHEMA VARCHAR(128) NOT NULL,
		TABLE_NAME VARCHAR(128) NOT NULL,
		IS_DEFERRABLE VARCHAR(3),
		INITIALLY_DEFERRED VARCHAR(3)
	);

CREATE TABLE ASSERTIONS (
		CONSTRAINT_CATALOG VARCHAR(128) NOT NULL,
		CONSTRAINT_SCHEMA VARCHAR(128) NOT NULL,
		CONSTRAINT_NAME VARCHAR(128) NOT NULL,
		IS_DEFERRABLE VARCHAR(3),
		INITIALLY_DEFERRED VARCHAR(3)
	);

CREATE TABLE TRIGGERS (
		TRIGGER_CATALOG VARCHAR(128) NOT NULL,
		TRIGGER_SCHEMA VARCHAR(128) NOT NULL,
		TRIGGER_NAME VARCHAR(128) NOT NULL,
		EVENT_MANIPULATION VARCHAR(128),
		EVENT_OBJECT_CATALOG VARCHAR(128),
		EVENT_OBJECT_SCHEMA VARCHAR(128),
		EVENT_OBJECT_TABLE VARCHAR(128),
		ACTION_ORDER BIGINT,
		ACTION_CONDITION VARCHAR(65536),
		ACTION_STATEMENT VARCHAR(65536),
		ACTION_ORIENTATION VARCHAR(65536),
		ACTION_TIMING VARCHAR(65536),
		ACTION_REFERENCE_OLD_TABLE VARCHAR(128),
		ACTION_REFERENCE_NEW_TABLE VARCHAR(128),
		ACTION_REFERENCE_OLD_ROW VARCHAR(128),
		ACTION_REFERENCE_NEW_ROW VARCHAR(128),
		CREATED TIMESTAMP
	);

CREATE TABLE TRIGGER_ROUTINE_USAGE (
		TRIGGER_CATALOG VARCHAR(128) NOT NULL,
		TRIGGER_SCHEMA VARCHAR(128) NOT NULL,
		TRIGGER_NAME VARCHAR(128) NOT NULL,
		SPECIFIC_CATALOG VARCHAR(128) NOT NULL,
		SPECIFIC_SCHEMA VARCHAR(128) NOT NULL,
		SPECIFIC_NAME VARCHAR(128) NOT NULL
	);

CREATE TABLE SQL_PACKAGES (
		ID VARCHAR(65536) NOT NULL,
		NAME VARCHAR(65536),
		IS_SUPPORTED VARCHAR(3),
		IS_VERIFIED_BY VARCHAR(65536),
		COMMENTS VARCHAR(65536)
	);

CREATE TABLE LOBS (
		BLOCK_ADDR INTEGER NOT NULL,
		BLOCK_COUNT INTEGER NOT NULL,
		BLOCK_OFFSET INTEGER NOT NULL,
		LOB_ID BIGINT NOT NULL
	);

CREATE TABLE SYSTEM_PRIMARYKEYS (
		TABLE_CAT VARCHAR(128) NOT NULL,
		TABLE_SCHEM VARCHAR(128) NOT NULL,
		TABLE_NAME VARCHAR(128) NOT NULL,
		COLUMN_NAME VARCHAR(128) NOT NULL,
		KEY_SEQ SMALLINT,
		PK_NAME VARCHAR(128)
	);

CREATE TABLE VIEW_ROUTINE_USAGE (
		VIEW_CATALOG VARCHAR(128) NOT NULL,
		VIEW_SCHEMA VARCHAR(128) NOT NULL,
		VIEW_NAME VARCHAR(128) NOT NULL,
		SPECIFIC_CATALOG VARCHAR(128) NOT NULL,
		SPECIFIC_SCHEMA VARCHAR(128) NOT NULL,
		SPECIFIC_NAME VARCHAR(128) NOT NULL
	);

CREATE TABLE AUTHORIZATIONS (
		AUTHORIZATION_NAME VARCHAR(128) NOT NULL,
		AUTHORIZATION_TYPE VARCHAR(128)
	);

CREATE TABLE TRIGGER_COLUMN_USAGE (
		TRIGGER_CATALOG VARCHAR(128) NOT NULL,
		TRIGGER_SCHEMA VARCHAR(128) NOT NULL,
		TRIGGER_NAME VARCHAR(128) NOT NULL,
		TABLE_CATALOG VARCHAR(128) NOT NULL,
		TABLE_SCHEMA VARCHAR(128) NOT NULL,
		TABLE_NAME VARCHAR(128) NOT NULL,
		COLUMN_NAME VARCHAR(128) NOT NULL
	);

CREATE TABLE SYSTEM_COLUMN_SEQUENCE_USAGE (
		TABLE_CATALOG VARCHAR(128) NOT NULL,
		TABLE_SCHEMA VARCHAR(128) NOT NULL,
		TABLE_NAME VARCHAR(128) NOT NULL,
		COLUMN_NAME VARCHAR(128) NOT NULL,
		SEQUENCE_CATALOG VARCHAR(128) NOT NULL,
		SEQUENCE_SCHEMA VARCHAR(128),
		SEQUENCE_NAME VARCHAR(128)
	);

CREATE TABLE CHARACTER_SETS (
		CHARACTER_SET_CATALOG VARCHAR(128) NOT NULL,
		CHARACTER_SET_SCHEMA VARCHAR(128) NOT NULL,
		CHARACTER_SET_NAME VARCHAR(128) NOT NULL,
		CHARACTER_REPERTOIRE VARCHAR(128),
		FORM_OF_USE VARCHAR(128),
		DEFAULT_COLLATE_CATALOG VARCHAR(128),
		DEFAULT_COLLATE_SCHEMA VARCHAR(128),
		DEFAULT_COLLATE_NAME VARCHAR(128)
	);

CREATE TABLE ROUTINE_ROUTINE_USAGE (
		SPECIFIC_CATALOG VARCHAR(128) NOT NULL,
		SPECIFIC_SCHEMA VARCHAR(128) NOT NULL,
		SPECIFIC_NAME VARCHAR(128) NOT NULL,
		ROUTINE_CATALOG VARCHAR(128) NOT NULL,
		ROUTINE_SCHEMA VARCHAR(128) NOT NULL,
		ROUTINE_NAME VARCHAR(128) NOT NULL
	);

CREATE TABLE SQL_FEATURES (
		FEATURE_ID VARCHAR(65536) NOT NULL,
		FEATURE_NAME VARCHAR(65536),
		SUB_FEATURE_ID VARCHAR(65536) NOT NULL,
		SUB_FEATURE_NAME VARCHAR(65536),
		IS_SUPPORTED VARCHAR(3),
		IS_VERIFIED_BY VARCHAR(65536),
		COMMENTS VARCHAR(65536)
	);

CREATE TABLE UDT_PRIVILEGES (
		GRANTOR VARCHAR(128) NOT NULL,
		GRANTEE VARCHAR(128) NOT NULL,
		UDT_CATALOG VARCHAR(128) NOT NULL,
		UDT_SCHEMA VARCHAR(128) NOT NULL,
		UDT_NAME VARCHAR(128) NOT NULL,
		PRIVILEGE_TYPE VARCHAR(65536),
		IS_GRANTABLE VARCHAR(3)
	);

CREATE TABLE SYSTEM_TABLETYPES (
		TABLE_TYPE VARCHAR(128) NOT NULL
	);

CREATE TABLE ROLE_UDT_GRANTS (
		GRANTOR VARCHAR(128),
		GRANTEE VARCHAR(128),
		UDT_CATALOG VARCHAR(128),
		UDT_SCHEMA VARCHAR(128),
		UDT_NAME VARCHAR(128),
		PRIVILEGE_TYPE VARCHAR(65536),
		IS_GRANTABLE VARCHAR(3)
	);

CREATE TABLE ENABLED_ROLES (
		ROLE_NAME VARCHAR(128) NOT NULL
	);

CREATE TABLE KEY_COLUMN_USAGE (
		CONSTRAINT_CATALOG VARCHAR(128) NOT NULL,
		CONSTRAINT_SCHEMA VARCHAR(128) NOT NULL,
		CONSTRAINT_NAME VARCHAR(128) NOT NULL,
		TABLE_CATALOG VARCHAR(128),
		TABLE_SCHEMA VARCHAR(128),
		TABLE_NAME VARCHAR(128),
		COLUMN_NAME VARCHAR(128) NOT NULL,
		ORDINAL_POSITION BIGINT NOT NULL,
		POSITION_IN_UNIQUE_CONSTRAINT BIGINT
	);

CREATE TABLE TRIGGER_SEQUENCE_USAGE (
		TRIGGER_CATALOG VARCHAR(128) NOT NULL,
		TRIGGER_SCHEMA VARCHAR(128) NOT NULL,
		TRIGGER_NAME VARCHAR(128) NOT NULL,
		SEQUENCE_CATALOG VARCHAR(128) NOT NULL,
		SEQUENCE_SCHEMA VARCHAR(128) NOT NULL,
		SEQUENCE_NAME VARCHAR(128) NOT NULL
	);

CREATE TABLE COLUMN_DOMAIN_USAGE (
		DOMAIN_CATALOG VARCHAR(128) NOT NULL,
		DOMAIN_SCHEMA VARCHAR(128) NOT NULL,
		DOMAIN_NAME VARCHAR(128) NOT NULL,
		TABLE_CATALOG VARCHAR(128) NOT NULL,
		TABLE_SCHEMA VARCHAR(128) NOT NULL,
		TABLE_NAME VARCHAR(128) NOT NULL,
		COLUMN_NAME VARCHAR(128) NOT NULL
	);

CREATE TABLE SYSTEM_PROCEDURECOLUMNS (
		PROCEDURE_CAT VARCHAR(128) NOT NULL,
		PROCEDURE_SCHEM VARCHAR(128) NOT NULL,
		PROCEDURE_NAME VARCHAR(128) NOT NULL,
		COLUMN_NAME VARCHAR(128),
		COLUMN_TYPE SMALLINT,
		DATA_TYPE SMALLINT,
		TYPE_NAME VARCHAR(128),
		PRECISION INTEGER,
		LENGTH INTEGER,
		SCALE SMALLINT,
		RADIX SMALLINT,
		NULLABLE SMALLINT,
		REMARKS VARCHAR(65536),
		COLUMN_DEF VARCHAR(65536),
		SQL_DATA_TYPE INTEGER,
		SQL_DATETIME_SUB INTEGER,
		CHAR_OCTET_LENGTH INTEGER,
		ORDINAL_POSITION INTEGER NOT NULL,
		IS_NULLABLE VARCHAR(65536),
		SPECIFIC_NAME VARCHAR(128) NOT NULL
	);

CREATE TABLE TRIGGER_TABLE_USAGE (
		TRIGGER_CATALOG VARCHAR(128) NOT NULL,
		TRIGGER_SCHEMA VARCHAR(128) NOT NULL,
		TRIGGER_NAME VARCHAR(128) NOT NULL,
		TABLE_CATALOG VARCHAR(128) NOT NULL,
		TABLE_SCHEMA VARCHAR(128) NOT NULL,
		TABLE_NAME VARCHAR(128) NOT NULL
	);

CREATE TABLE DATA_TYPE_PRIVILEGES (
		OBJECT_CATALOG VARCHAR(128) NOT NULL,
		OBJECT_SCHEMA VARCHAR(128) NOT NULL,
		OBJECT_NAME VARCHAR(128) NOT NULL,
		OBJECT_TYPE VARCHAR(128) NOT NULL,
		DTD_IDENTIFIER VARCHAR(128) NOT NULL
	);

CREATE UNIQUE INDEX SYS_IDX_LOBS_PK_10006 ON LOBS (LOB_ID ASC, BLOCK_OFFSET ASC);

CREATE UNIQUE INDEX SYS_IDX_BLOCKS_PK_10003 ON BLOCKS (BLOCK_ADDR ASC);

CREATE UNIQUE INDEX SYS_IDX_LOB_IDS_PK_10011 ON LOB_IDS (LOB_ID ASC);

CREATE INDEX LOBS_IDX2 ON LOB_IDS (LOB_USAGE_COUNT ASC);

CREATE UNIQUE INDEX SYS_IDX_LOBS_UQ1_10007 ON LOBS (BLOCK_ADDR ASC);

CREATE INDEX BLOCKS_IDX1 ON BLOCKS (BLOCK_COUNT ASC);

ALTER TABLE BLOCKS ADD CONSTRAINT BLOCKS_PK PRIMARY KEY (BLOCK_ADDR);

ALTER TABLE LOBS ADD CONSTRAINT LOBS_PK PRIMARY KEY (LOB_ID, BLOCK_OFFSET);

ALTER TABLE LOB_IDS ADD CONSTRAINT LOB_IDS_PK PRIMARY KEY (LOB_ID);

